### ISSUE TITLE
Node exporter doesn't handle SIGHUP

### ISSUE THREAD

**Issue by mlosapio** [William-Yeh/ansible-prometheus#20]
Running kill HUP will terminate the process...

**Comment by lae** [comment]
Shouldn't you report this to the node_exporter project? What exactly are you expecting, though?

**Comment by mlosapio** [comment]
Well you're saying the project should support your unit script. It's the other way around. You should remove reload since it's not going to reload anything. Or alias reload to restart.

**Comment by lae** [comment]
It wasn't clear that you were talking about the init scripts for node exporter.

Agreed though, there are no instances where node_exporter is reloaded in this role so it's just a bit of code bloat. I'll open a PR (I'm not a maintainer of this role) for this later if you don't want to.

**Comment by William-Yeh** [comment]
I've encountered the same issue for node_exporter (and maybe some other Prometheus projects as well).  I'll try to verify if it's a problem in the Prometheus itself.
