### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by lae** [William-Yeh/ansible-prometheus#21]
@William-Yeh There have been official debian packages for Prom and node_exporter in Debian testing since last June. Would you want to base service files from them in this role?

https://packages.debian.org/stretch/prometheus
https://packages.debian.org/stretch/prometheus-node-exporter

**Comment by William-Yeh** [comment]
I'll check it out.

But I'm afraid that I'll adopt only its INIT (systemd?) part.

**Comment by lae** [comment]
I'm already working on it in a local branch, if you want to wait for that.

**Comment by jvelo** [comment]
Hi @lae is this your fork : https://github.com/lae/ansible-role-prometheus ?
I have it running properly using the same configuration documented for this repos. Any chance to have this merged upstream @William-Yeh ? Anything I could do to help ?

**Comment by lae** [comment]
Hi @jvelo, that is not a fork (https://github.com/lae/williamyeh-prometheus is). I'm also planning on doing some things differently from this role, such as separating node_exporter. It doesn't yet handle configuration though since I was on vacation for a bit.
