### ISSUE TITLE
systemd support for prometheus and alertmanager

### ISSUE THREAD

**Issue by wtip** [William-Yeh/ansible-prometheus#30]
Adding systemd support for prometheus and alertmanager would be nice.
Any particular reason why this was only added for node_exporter?

**Comment by ecksun** [comment]
I got the following error while trying to use this in its current form:

    fatal: [server]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'prometheus'\": "}

I did not investigate it much but instead started to work in adding support for systemd for prometheus and alertmanager, hopefully I can send a PR relatively soon.

**Comment by William-Yeh** [comment]
Modified since https://github.com/William-Yeh/ansible-prometheus/tree/2.5.0
