### ISSUE TITLE
"with_dict expects a dict" in ansible-2.2.0.0

### ISSUE THREAD

**Issue by reinysong-gogolook** [William-Yeh/ansible-prometheus#31]
While using ansible 2.2, there will be an error:

TASK [williamyeh.prometheus : copy rule files from playbook's, if any] *********
task path: /private/etc/ansible/roles/williamyeh.prometheus/tasks/install-prometheus.yml:145
fatal: [hive]: FAILED! => {
    "failed": true, 
    "msg": "with_dict expects a dict"
}

**Comment by William-Yeh** [comment]
Fixed since 2.3.2 of this role.
