### ISSUE TITLE
Prometheus 0.16.0rc1 upgrade strategy

### ISSUE THREAD

**Issue by robbiet480** [William-Yeh/ansible-prometheus#5]
There are quite a few breaking changes in the most recent Prometheus release, [0.16.0rc1](https://github.com/prometheus/prometheus/releases/tag/0.16.0rc1). They are core enough changes that my simple setup is now broken. Instead of updating the Prometheus version number in this repo and possibly leaving people's systems broken, we may need to come up with a different solution...

**Comment by William-Yeh** [comment]
Thanks.

I've fixed this 0.16.0rc1 issue in https://github.com/William-Yeh/ansible-prometheus/commit/64027831fbc966c0a47730bcefac84f8e8ae1608

**Comment by robbiet480** [comment]
@William-Yeh Good fix for the re-organization of the release files. However, I was also speaking about the [breaking configuration changes](https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md#0160rc1--2015-09-18). Maybe it would be best to leave the current version at the last stable (0.15.1) and make users manually set the variable to 0.16.0rc1 and above?
