### ISSUE TITLE
Playbook not working

### ISSUE THREAD

**Issue by ppanucool** [William-Yeh/ansible-prometheus#51]
Hi all,

I tried to run the playbook (test.yml)
root@ip-10-0-0-253:~# cat test.yaml 
---
- hosts: all
  become: True
  roles:
    - mkrakowitzer.prometheus

  vars:
    prometheus_components: [ "prometheus", "alertmanager", "node_exporter" ]
    prometheus_alertmanager_url: "http://localhost:9093/"

**Got following error while running the playbook :**
root@ip-10-0-0-253:~# ansible-playbook -i "localhost," -c local test.yaml 

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [mkrakowitzer.prometheus : include] ***************************************
included: /etc/ansible/roles/mkrakowitzer.prometheus/tasks/install.yml for localhost

TASK [mkrakowitzer.prometheus : install deps (Ubuntu)] *************************
ok: [localhost] => (item=[u'python-pip', u'jq'])

TASK [mkrakowitzer.prometheus : install deps (RHEL)] ***************************
skipping: [localhost] => (item=[]) 

TASK [mkrakowitzer.prometheus : pip] *******************************************
ok: [localhost]

TASK [mkrakowitzer.prometheus : include] ***************************************
fatal: [localhost]: FAILED! => {"failed": true, "reason": "ERROR! no action detected in task\n\nThe error appears to have been in '/etc/ansible/roles/mkrakowitzer.prometheus/tasks/install-prometheus.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Create prometheus container\n  ^ here\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1   

**Thanks for any help !!**

**Comment by oppai** [comment]
This playbook repository is not `mkrakowitzer.prometheus`.
Please check https://github.com/mkrakowitzer/ansible-prometheus
