### ISSUE TITLE
node_exporter.service doesn't start at boot

### ISSUE THREAD

**Issue by mathieumd** [William-Yeh/ansible-prometheus#55]
After rebooting the machines where only `node_exporter` was installed through this nice role, the `node_exporter.service` Systemd unit does not start.

If I try to enable it manually:
```
sudo systemctl enable node_exporter.service
The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
settings in the [Install] section, and DefaultInstance for template units).
This means they are not meant to be enabled using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
4) In case of template units, the unit is meant to be enabled with some
   instance name specified.
```

Starting it manually does work. But, obviously, we need to have it started at each boot! 😄

Appending this `[Install]` block to [/lib/systemd/system/node_exporter.service](https://github.com/William-Yeh/ansible-prometheus/blob/master/templates/node_exporter.service.j2) should suffice:

```
[Install]
WantedBy=network-online.target
```

**Comment by William-Yeh** [comment]
Modified since https://github.com/William-Yeh/ansible-prometheus/tree/2.5.0
