### ISSUE TITLE
Prometheus 2.0 - task fails "copy prometheus main config file from role's default, if necessary"

### ISSUE THREAD

**Issue by jensbaitingerbosch** [William-Yeh/ansible-prometheus#56]
With prometheus 2.0 the options for promtool changed. Previously it was "check-config" now it is "check config" (space instead of collon). Same with "check-rules", which is now "check rules".
Therefore the task "copy prometheus main config file from role's default, if necessary" (if you use the default config and the analoguous step for non-default config failes.

**Comment by madeinoz67** [comment]
thanks for that I was getting the same error, unfortunately it looks as though this role in not being actively maintained.

**Comment by rdemachkovych** [comment]
We have active maintained the [ansible roles](https://github.com/SoInteractive/ansible-prometheus) with support Prometheus 2.0 (release 0.6.1 support both 1.x.x and 2.0 version)
Right now this role is in early development and if you have any ideas what can be done there, we'll gladly hear them.
We would also like to add the role to Prometheus documentation ([PR #3505](https://github.com/prometheus/prometheus/pull/3505#pullrequestreview-78539837))

**Comment by lhoss** [comment]
did you try https://github.com/William-Yeh/ansible-prometheus/pull/57 ?

ps: In the hope to bring the master branch up to speed: https://github.com/William-Yeh/ansible-prometheus/issues/64

**Comment by frisellcpl** [comment]
I fixed the problem by replacing the command "./promtool check-config" with the new syntax "./promtool check config" and respectively "check-rules" to "check rules".

**Comment by William-Yeh** [comment]
Updated since https://github.com/William-Yeh/ansible-prometheus/tree/2.5.0
