### ISSUE TITLE
set-role-variables - Condition is wrong evaluated for ansible_distribution_version

### ISSUE THREAD

**Issue by colandre** [William-Yeh/ansible-prometheus#58]
Hello,

as I reported also [here](https://github.com/abednarik/ansible-role-mysqld-exporter/issues/3#issuecomment-345473880), there is a problem with the set-role-variables.yml.

Let me report it:
I think that in file set-role-variables.yml there would be a problem with the "when" condition.

when: ansible_distribution == "CentOS" and ansible_distribution_version|int >= 7
In my case, the fact ansible_distribution_version is evaluated with 7.2.1511 and passing it through the |int function, it returns "0", due to multiple dots separator.

How to replicate:
```
ansible -vvv -i localhost, -c local -m debug -a "var={{ '7.2.1511' | int }}" all
```
I think that a better variable that can be used for the when condition could be: ```
```
ansible_distribution_major_version
```
(The result of this issue is for me the installation of the mysql_exporter deamon as service in /etc/init.d instead of place the service in /etc/systemd/system folder. I'm running CentOS v7.2.1511)

**Comment by William-Yeh** [comment]
Updated since https://github.com/William-Yeh/ansible-prometheus/tree/2.5.0
