### ISSUE TITLE
Possible to have more role maintainers, to manage the PR Fixes/Improvements ?!

### ISSUE THREAD

**Issue by lhoss** [William-Yeh/ansible-prometheus#64]
In the current repository, progress is hindered due to a lack of PR maintenance, despite the many nice PR contributions by some happy role users.
Maybe the current maintainer (@William-Yeh ) can offer maintainer status to interested parties, so we can bring this role forward !
Thanks and merry Xmas 👍 

----
I went through some forks to see which ones are quite ahead of the official repos, also by merging some of the PR (still open here), which could be a good new start point:
* Most advanced fork, many PRs merged (incl from teralytics -v), 26 commits ahead: https://github.com/William-Yeh/ansible-prometheus/compare/master...pieterlexis:master
* Fork (of our company), 11 commits ahead: https://github.com/William-Yeh/ansible-prometheus/compare/master...teralytics:master
* Fork incl. node_exporter restart, 6 commits ahead: https://github.com/William-Yeh/ansible-prometheus/compare/master...Reisegiganten:master
* Finally a fork with many changes, but deviating, and forked from another fork (`This branch is 111 commits ahead, 90 commits behind ajmaidak:master.`) https://github.com/thknepper/ansible-prometheus

**Comment by BlessJah** [comment]
Maybe you could publish competitive role on galaxy?

CC @pieterlexis @teralytics

**Comment by BlessJah** [comment]
@lhoss last one you've listed is actually fork of **ajmaidak** which in turn is fork of this repo. It seems that at some point **ajmaidak** ran wrong `git filter-branch` command and **thknepper** forked the mistake was fixed.

Here is the only comparision that makes sense for **William-Yeh/ansible-prometheus**, **thknepper/ansible-prometheus** and **ajmaidak/ansible-prometheus**:
https://github.com/William-Yeh/ansible-prometheus/compare/master...ajmaidak:altmaster

**Comment by eliecharra** [comment]
The main purpose here is to find someone who could have time to maintain this role @BlessJah @lhoss.
After that, we need a fork free of company specific code (I dont ave inspected below forks), but I'd rather prefer to create a new clean fork and integrate pending PR afterwhile.

I can fork and publish a clean new role on galaxy and give maintainer roles but I dont have time to maintain it actively :cry:

**Comment by eliecharra** [comment]
Forked here 

https://galaxy.ansible.com/kibatic/prometheus
https://github.com/kibatic/ansible-prometheus

One commit of diff: https://github.com/kibatic/ansible-prometheus/commit/25dd64069e1f4f47c88429a125d7d65bebfa9818

Lemme know if some of you wanna be a maintainer of forked role.

**Comment by lae** [comment]
I'm sure some people have discovered these already, but in case passersby here have not - the folks over at Cloud Alchemy have brought up and maintain separate roles (which honestly makes more sense than having one role for deploying both prometheus and node_exporter) for the various parts of the Prometheus ecosystem (including one for Grafana!) that I've been using successfully for a short bit. They have a demo playbook as well.

https://github.com/cloudalchemy

(their node_exporter role however only supports systemd-based systems - there's a fork @idolactivities that adds Ubuntu 14 upstart support and should soon add sysvinit for CentOS 6 and maybe OpenRC systems as well)

**Comment by William-Yeh** [comment]
Sorry for late response.

I've been moved most of my personal and my company's configuration to the Docker ecosystem. So I'll not actively maintain Ansible-related work.  Feel free to fork mine or move to another alternatives.
