### ISSUE TITLE
prometheus.service not starting correctly with prometheus 2.0.0

### ISSUE THREAD

**Issue by jtexier** [William-Yeh/ansible-prometheus#65]
Trying to launch prometheus.service 
`systemctl start prometheus`
installed with prometheus 2.0.0 fails with the following message :  
`prometheus: error: unknown short flag '-c'`

The reason is options have changed on prometheus 2.0.0 versus 1.5.
-config.file has become --config.file
-storage.local.path has become --storage.tsdb.path 
-web* options have become --web*

Then /etc/init.d/prometheus file should be edited this way :  

`
DAEMON_OPTS="$DAEMON_OPTS --config.file=$CONFIG  --storage.tsdb.path=/var/lib/prometheus"
DAEMON_OPTS="$DAEMON_OPTS --web.console.templates=/opt/prometheus/prometheus-2.0.0.linux-amd64/consoles  --web.console.libraries=/opt/prometheus/prometheus-2.0.0.linux-amd64/console_libraries" 
`

**Comment by William-Yeh** [comment]
Updated since https://github.com/William-Yeh/ansible-prometheus/tree/2.5.0
