### ISSUE TITLE
alertmanager fails if alertmanager.conf does not exist

### ISSUE THREAD

**Issue by jasco** [William-Yeh/ansible-prometheus#9]
The role currently copies the optional user provided alertmanager.conf _after_ trying to start the service which resulted in a failure with an error complaining the config file was not found.  Either the user supplied conf or some default should be in place prior to starting the server.

An empty alertmanager.conf seems sufficient to keep it from failing, but I have not used alertmanager yet so I am not sure if any empty conf is an appropriate default or not.

**Comment by William-Yeh** [comment]
Thank you!
